Adding note for initial commit requirement during quickstart
xigxog/kubefox pull request #26
Opened 2024-03-31 00:38 UTC by BryanFauble

**Problem:**
- During the quickstart docs it has you do:
```
mkdir kubefox-quickstart && \
  cd kubefox-quickstart && \
  export FOX_INFO=true && \
  fox init --quickstart
```
(The same as the screenshot below, but I did it over multiple steps as I was debugging the issue in the first place)

- After this init it is followed up by 2 steps later by:
```
fox publish --wait 5m
```

However - This fails as this is a newly create git repo with no existing commits:
![image](https://github.com/xigxog/kubefox/assets/17128019/f32dc6ca-935d-4658-ab69-f6c7e2cd8467)

**Solution:**
- I was able to just add a commit with all of the initial example files and `fox publish` as expected

**Testing:**
- I verified on an Arch linux distro that I was able to follow the full quickstart guide from start to end

2024-03-31 00:57 UTC, BryanFauble commented
@xadhatter There are 2 quickstart.md files. The one at `docs/quickstart.md` doesn't appear to be referenced anywhere; They are identical. Do they both need to exist, or can I removed `docs/quickstart.md`?

2024-04-01 15:22 UTC, xadhatter commented
> @xadhatter There are 2 quickstart.md files. The one at `docs/quickstart.md` doesn't appear to be referenced anywhere; They are identical. Do they both need to exist, or can I removed `docs/quickstart.md`?

We had sent out material with links to the Quickstart in the root docs directory so we temporarily left it. It'd be better to leave the page but have it redirect to the Quickstart under `Getting Started`.

2024-04-01 15:24 UTC, xadhatter commented
> However - This fails as this is a newly create git repo with no existing commits:



This appears to be a bug in the Fox CLI. Can you send the output of `git status` after you perform the `fox init` command?

Thanks so much for taking the time to test and for the PR.

2024-04-07 22:58 UTC, BryanFauble commented
> > However - This fails as this is a newly create git repo with no existing commits:
> 
> This appears to be a bug in the Fox CLI as it should be performing the initial commit. Can you send the output of `fox --verbose init` followed by `git status`?
> 
> Thanks so much for taking the time to test and for the PR.

I went through and verified that it was a missing `~/.gitconfig`. When it is missing and an error occurs we do get back:
`error   😖 Error committing changes: author field is required`

I verified that after adding `~/.gitconfig` this worked as expected.

2024-04-07 23:01 UTC, BryanFauble commented on docs/quickstart.md
> +<meta http-equiv="refresh" content="0; url=getting_started/quickstart.html" />
@xadhatter This appears to work as expected when I deploy the mkdocs to my local machine - In lieu of the automatic redirect working I added in a manual button they can click to go to the new page.

2024-04-10 16:06 UTC, xadhatter requested changes
Nice fix. Thanks.

2024-04-10 16:07 UTC, xadhatter approved these changes

2024-04-10 16:07 UTC, merged